<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Dalamud.NET.Sdk/15.0.0">
  <PropertyGroup>
    <Version>1.0.0.0</Version>
    <Author>katabame</Author>
    <Name>FateTracker</Name>
    <Punchline>FATEトラッカー</Punchline>
    <Description>FATEの進行状況を追跡するプラグインです</Description>
    <RepoUrl>https://github.com/katabame/DalamudTemplate</RepoUrl>
    <Tags>FATE;track</Tags>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Update="DotNet.ReproducibleBuilds" Version="2.0.5" />
  </ItemGroup>
</Project>
