<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Dalamud.NET.Sdk/15.0.0">
  <PropertyGroup>
    <Version>1.0.0.0</Version>
    <Author>katabame</Author>
    <Name>DalamudTemplate</Name>
    <Punchline>テンプレートプラグイン</Punchline>
    <Description>Dalamudのテンプレートプラグインです</Description>
    <RepoUrl>https://github.com/katabame/DalamudTemplate</RepoUrl>
    <Tags>plugin;katabame</Tags>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Update="DotNet.ReproducibleBuilds" Version="2.0.5" />
  </ItemGroup>
</Project>
